import { createContext, useContext, useState, type ReactNode } from 'react'

type Language = 'ko' | 'en' | 'zh'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  ko: {
    'onboarding.upload.title': '나의 영상 올리기',
    'onboarding.upload.desc': '소중한 순간의 사진을 선택하세요',
    'onboarding.ai.title': 'AI 입체 변환',
    'onboarding.ai.desc': 'AI가 입체감 있는 홀로그램을 만듭니다',
    'onboarding.theme.title': '테마 선택',
    'onboarding.theme.desc': '아름다운 배경과 테마를 선택하세요',
    'onboarding.display.title': '영원히 간직',
    'onboarding.display.desc': 'Eternal Beam 기기로 영원히 간직하세요',
    'onboarding.skip': '건너뛰기',
    'onboarding.next': '다음',
    'onboarding.start': '시작하기',
    'home.welcome': '환영합니다',
    'home.create': '새로운 추억 만들기',
    'home.holograms': '나의 홀로그램',
    'home.viewAll': '전체보기',
    'home.nav.home': '홈',
    'home.nav.gallery': '갤러리',
    'home.nav.device': '기기',
    'home.nav.settings': '설정',
    'gallery.title': '갤러리',
    'gallery.recent': '최근 추억',
    'gallery.favorites': '즐겨찾기',
    'gallery.all': '전체보기',
    'gallery.empty': '아직 추억이 없습니다',
    'gallery.create': '첫 번째 추억 만들기',
    'upload.title': '사진 선택',
    'upload.desc': '홀로그램으로 만들 사진을 선택하세요',
    'upload.device': '기기에서 선택',
    'upload.gallery': '갤러리에서 선택',
    'upload.camera': '카메라로 촬영',
    'upload.drag': '또는 여기에 드래그하세요',
    'aiprocess.title': 'AI 변환 중',
    'aiprocess.analyzing': '사진 분석 중...',
    'aiprocess.depth': '깊이 맵 생성 중...',
    'aiprocess.rendering': '3D 렌더링 중...',
    'aiprocess.finalizing': '최종 처리 중...',
    'aiprocess.complete': '변환 완료!',
    'aiprocess.next': '다음 단계',
    'theme.title': '테마 선택',
    'theme.desc': '홀로그램 배경 테마를 선택하세요',
    'theme.christmas': '크리스마스 원더',
    'theme.sunset': '석양 해변',
    'theme.forest': '숲의 꿈',
    'theme.memorial': '추모의 빛',
    'theme.galaxy': '우주 여행',
    'theme.sakura': '벚꽃 정원',
    'theme.ocean': '심해 탐험',
    'theme.aurora': '오로라 빛',
    'theme.next': '다음',
    'record.title': '음성 메시지 녹음',
    'record.desc': '홀로그램에 담을 목소리를 녹음하세요',
    'record.start': '녹음 시작',
    'record.stop': '녹음 중지',
    'record.recording': '녹음 중...',
    'record.duration': '최대 60초',
    'record.play': '재생',
    'record.delete': '삭제',
    'record.save': '저장하고 계속',
    'record.tip': '조용한 곳에서 녹음하세요',
    'voice.recorded': '녹음 완료',
    'qr.title': 'QR 코드로 연결',
    'qr.desc': '기기의 QR 코드를 스캔하세요',
    'qr.scanning': '카메라 스캔 중...',
    'qr.manual': '수동으로 코드 입력',
    'qr.connected': '연결됨!',
    'qr.error': '연결 실패',
    'nfc.title': 'NFC 전송',
    'nfc.desc': '기기를 휴대폰에 가까이 대세요',
    'nfc.ready': '전송 준비됨',
    'nfc.transferring': '전송 중...',
    'nfc.complete': '전송 완료!',
    'nfc.error': 'NFC를 지원하지 않는 기기입니다',
    'complete.title': '완료!',
    'complete.desc': '홀로그램이 기기로 전송되었습니다',
    'complete.view': '기기에서 보기',
    'complete.home': '홈으로',
    'complete.share': '친구에게 공유',
    'device.title': '기기 관리',
    'device.connected': '연결된 기기',
    'device.add': '새 기기 추가',
    'device.status.online': '온라인',
    'device.status.offline': '오프라인',
    'device.battery': '배터리',
    'device.storage': '저장공간',
    'device.storageUsed': '사용됨',
    'device.sync': '동기화',
    'device.settings': '기기 설정',
    'device.remove': '기기 제거',
    'device.firmware': '펌웨어 업데이트',
    'payment.title': '결제',
    'payment.desc': '프리미엄 플랜으로 업그레이드',
    'payment.basic': '베이직',
    'payment.premium': '프리미엄',
    'payment.pro': '프로',
    'payment.free': '무료',
    'payment.month': '월',
    'payment.year': '년',
    'payment.holograms': '개 홀로그램',
    'payment.storage': '저장공간',
    'payment.themes': '프리미엄 테마',
    'payment.support': '우선 지원',
    'payment.select': '선택하기',
    'payment.current': '현재 플랜',
    'payment.method': '결제 수단',
    'payment.card': '카드 결제',
    'payment.toss': '토스페이',
    'payment.confirm': '결제하기',
    'payment.popular': '인기',
    'payment.easyDesc': '간편하고 빠른 결제',
    'payment.cardDesc': '신용카드 / 체크카드',
    'payment.currency': '원',
    'payment.api': 'API 접근',
    'payment.feat.5holograms': '5개 홀로그램',
    'payment.feat.50holograms': '50개 홀로그램',
    'payment.feat.unlimitedHolograms': '무제한 홀로그램',
    'payment.feat.1gb': '1GB 저장공간',
    'payment.feat.10gb': '10GB 저장공간',
    'payment.feat.100gb': '100GB 저장공간',
    'payment.feat.basicTheme': '기본 테마',
    'payment.feat.premiumTheme': '프리미엄 테마',
    'payment.feat.allThemes': '모든 테마',
    'payment.feat.prioritySupport': '우선 지원',
    'payment.feat.vipSupport': 'VIP 지원',
    'settings.title': '설정',
    'settings.account': '계정',
    'settings.profile': '프로필 수정',
    'settings.language': '언어',
    'settings.notifications': '알림',
    'settings.push': '푸시 알림',
    'settings.email': '이메일 알림',
    'settings.privacy': '개인정보',
    'settings.terms': '이용약관',
    'settings.policy': '개인정보처리방침',
    'settings.version': '버전',
    'settings.logout': '로그아웃',
    'settings.delete': '계정 삭제',
    'settings.support': '고객 지원',
    'settings.faq': '자주 묻는 질문',
    'settings.contact': '문의하기',
  },
  en: {
    'onboarding.upload.title': 'Upload Your Memory',
    'onboarding.upload.desc': 'Choose a cherished photo',
    'onboarding.ai.title': 'AI Processing',
    'onboarding.ai.desc': 'Our AI creates stunning 3D holograms',
    'onboarding.theme.title': 'Choose a Theme',
    'onboarding.theme.desc': 'Select from beautiful backgrounds',
    'onboarding.display.title': 'Display Forever',
    'onboarding.display.desc': 'Sync to your Eternal Beam device',
    'onboarding.skip': 'Skip',
    'onboarding.next': 'Next',
    'onboarding.start': 'Get Started',
    'home.welcome': 'Welcome back',
    'home.create': 'Create New Memory',
    'home.holograms': 'My Holograms',
    'home.viewAll': 'View All',
    'home.nav.home': 'Home',
    'home.nav.gallery': 'Gallery',
    'home.nav.device': 'Device',
    'home.nav.settings': 'Settings',
    'gallery.title': 'Gallery',
    'gallery.recent': 'Recent Memories',
    'gallery.favorites': 'Favorites',
    'gallery.all': 'View All',
    'gallery.empty': 'No memories yet',
    'gallery.create': 'Create your first memory',
    'upload.title': 'Select Photo',
    'upload.desc': 'Choose a photo to convert into hologram',
    'upload.device': 'From Device',
    'upload.gallery': 'From Gallery',
    'upload.camera': 'Take Photo',
    'upload.drag': 'Or drag here',
    'aiprocess.title': 'AI Processing',
    'aiprocess.analyzing': 'Analyzing photo...',
    'aiprocess.depth': 'Generating depth map...',
    'aiprocess.rendering': 'Rendering 3D...',
    'aiprocess.finalizing': 'Finalizing...',
    'aiprocess.complete': 'Complete!',
    'aiprocess.next': 'Next Step',
    'theme.title': 'Choose Theme',
    'theme.desc': 'Select a background theme for your hologram',
    'theme.christmas': 'Christmas Wonder',
    'theme.sunset': 'Sunset Beach',
    'theme.forest': 'Forest Dream',
    'theme.memorial': 'Memorial Light',
    'theme.galaxy': 'Space Journey',
    'theme.sakura': 'Sakura Garden',
    'theme.ocean': 'Deep Ocean',
    'theme.aurora': 'Aurora Light',
    'theme.next': 'Next',
    'record.title': 'Record Voice Message',
    'record.desc': 'Record your voice for the hologram',
    'record.start': 'Start Recording',
    'record.stop': 'Stop Recording',
    'record.recording': 'Recording...',
    'record.duration': 'Max 60 seconds',
    'record.play': 'Play',
    'record.delete': 'Delete',
    'record.save': 'Save & Continue',
    'record.tip': 'Record in a quiet place',
    'voice.recorded': 'Recording complete',
    'qr.title': 'Connect via QR Code',
    'qr.desc': 'Scan the QR code on your device',
    'qr.scanning': 'Camera scanning...',
    'qr.manual': 'Enter code manually',
    'qr.connected': 'Connected!',
    'qr.error': 'Connection failed',
    'nfc.title': 'NFC Transfer',
    'nfc.desc': 'Bring device close to your phone',
    'nfc.ready': 'Ready to transfer',
    'nfc.transferring': 'Transferring...',
    'nfc.complete': 'Transfer complete!',
    'nfc.error': 'NFC not supported',
    'complete.title': 'Complete!',
    'complete.desc': 'Hologram sent to device',
    'complete.view': 'View on device',
    'complete.home': 'Go Home',
    'complete.share': 'Share with friends',
    'device.title': 'Device Management',
    'device.connected': 'Connected Devices',
    'device.add': 'Add New Device',
    'device.status.online': 'Online',
    'device.status.offline': 'Offline',
    'device.battery': 'Battery',
    'device.storage': 'Storage',
    'device.storageUsed': 'used',
    'device.sync': 'Sync',
    'device.settings': 'Device Settings',
    'device.remove': 'Remove Device',
    'device.firmware': 'Firmware Update',
    'payment.title': 'Payment',
    'payment.desc': 'Upgrade to Premium',
    'payment.basic': 'Basic',
    'payment.premium': 'Premium',
    'payment.pro': 'Pro',
    'payment.free': 'Free',
    'payment.month': 'month',
    'payment.year': 'year',
    'payment.holograms': 'holograms',
    'payment.storage': 'storage',
    'payment.themes': 'Premium themes',
    'payment.support': 'Priority support',
    'payment.select': 'Select',
    'payment.current': 'Current Plan',
    'payment.method': 'Payment Method',
    'payment.card': 'Credit Card',
    'payment.toss': 'Toss Pay',
    'payment.confirm': 'Confirm Payment',
    'payment.popular': 'Popular',
    'payment.easyDesc': 'Easy and fast payment',
    'payment.cardDesc': 'Credit / Debit card',
    'payment.currency': ' KRW',
    'payment.api': 'API access',
    'payment.feat.5holograms': '5 holograms',
    'payment.feat.50holograms': '50 holograms',
    'payment.feat.unlimitedHolograms': 'Unlimited holograms',
    'payment.feat.1gb': '1GB storage',
    'payment.feat.10gb': '10GB storage',
    'payment.feat.100gb': '100GB storage',
    'payment.feat.basicTheme': 'Basic theme',
    'payment.feat.premiumTheme': 'Premium theme',
    'payment.feat.allThemes': 'All themes',
    'payment.feat.prioritySupport': 'Priority support',
    'payment.feat.vipSupport': 'VIP support',
    'settings.title': 'Settings',
    'settings.account': 'Account',
    'settings.profile': 'Edit Profile',
    'settings.language': 'Language',
    'settings.notifications': 'Notifications',
    'settings.push': 'Push Notifications',
    'settings.email': 'Email Notifications',
    'settings.privacy': 'Privacy',
    'settings.terms': 'Terms of Service',
    'settings.policy': 'Privacy Policy',
    'settings.version': 'Version',
    'settings.logout': 'Logout',
    'settings.delete': 'Delete Account',
    'settings.support': 'Support',
    'settings.faq': 'FAQ',
    'settings.contact': 'Contact Us',
  },
  zh: {
    'onboarding.upload.title': '上传您的记忆',
    'onboarding.upload.desc': '选择珍贵的照片',
    'onboarding.ai.title': 'AI 处理',
    'onboarding.ai.desc': '我们的AI创建令人惊叹的3D全息图',
    'onboarding.theme.title': '选择主题',
    'onboarding.theme.desc': '选择美丽的背景',
    'onboarding.display.title': '永久展示',
    'onboarding.display.desc': '同步到您的 Eternal Beam 设备',
    'onboarding.skip': '跳过',
    'onboarding.next': '下一步',
    'onboarding.start': '开始',
    'home.welcome': '欢迎回来',
    'home.create': '创建新记忆',
    'home.holograms': '我的全息图',
    'home.viewAll': '查看全部',
    'home.nav.home': '主页',
    'home.nav.gallery': '图库',
    'home.nav.device': '设备',
    'home.nav.settings': '设置',
    'gallery.title': '图库',
    'gallery.recent': '最近的记忆',
    'gallery.favorites': '收藏夹',
    'gallery.all': '查看全部',
    'gallery.empty': '还没有记忆',
    'gallery.create': '创建您的第一个记忆',
    'upload.title': '选择照片',
    'upload.desc': '选择要转换为全息图的照片',
    'upload.device': '从设备',
    'upload.gallery': '从图库',
    'upload.camera': '拍照',
    'upload.drag': '或拖到这里',
    'aiprocess.title': 'AI 处理中',
    'aiprocess.analyzing': '分析照片中...',
    'aiprocess.depth': '生成深度图...',
    'aiprocess.rendering': '3D 渲染中...',
    'aiprocess.finalizing': '最后处理中...',
    'aiprocess.complete': '完成！',
    'aiprocess.next': '下一步',
    'theme.title': '选择主题',
    'theme.desc': '为您的全息图选择背景主题',
    'theme.christmas': '圣诞奇迹',
    'theme.sunset': '日落海滩',
    'theme.forest': '森林之梦',
    'theme.memorial': '纪念之光',
    'theme.galaxy': '太空之旅',
    'theme.sakura': '樱花园',
    'theme.ocean': '深海探索',
    'theme.aurora': '极光',
    'theme.next': '下一步',
    'record.title': '录制语音消息',
    'record.desc': '为全息图录制您的声音',
    'record.start': '开始录制',
    'record.stop': '停止录制',
    'record.recording': '录制中...',
    'record.duration': '最多60秒',
    'record.play': '播放',
    'record.delete': '删除',
    'record.save': '保存并继续',
    'record.tip': '请在安静的地方录制',
    'voice.recorded': '录制完成',
    'qr.title': '通过二维码连接',
    'qr.desc': '扫描设备上的二维码',
    'qr.scanning': '相机扫描中...',
    'qr.manual': '手动输入代码',
    'qr.connected': '已连接！',
    'qr.error': '连接失败',
    'nfc.title': 'NFC传输',
    'nfc.desc': '将设备靠近手机',
    'nfc.ready': '准备传输',
    'nfc.transferring': '传输中...',
    'nfc.complete': '传输完成！',
    'nfc.error': '不支持NFC',
    'complete.title': '完成！',
    'complete.desc': '全息图已发送到设备',
    'complete.view': '在设备上查看',
    'complete.home': '返回主页',
    'complete.share': '分享给朋友',
    'device.title': '设备管理',
    'device.connected': '已连接设备',
    'device.add': '添加新设备',
    'device.status.online': '在线',
    'device.status.offline': '离线',
    'device.battery': '电池',
    'device.storage': '存储',
    'device.storageUsed': '已使用',
    'device.sync': '同步',
    'device.settings': '设备设置',
    'device.remove': '移除设备',
    'device.firmware': '固件更新',
    'payment.title': '支付',
    'payment.desc': '升级到高级版',
    'payment.basic': '基础版',
    'payment.premium': '高级版',
    'payment.pro': '专业版',
    'payment.free': '免费',
    'payment.month': '月',
    'payment.year': '年',
    'payment.holograms': '个全息图',
    'payment.storage': '存储空间',
    'payment.themes': '高级主题',
    'payment.support': '优先支持',
    'payment.select': '选择',
    'payment.current': '当前方案',
    'payment.method': '支付方式',
    'payment.card': '信用卡',
    'payment.toss': 'Toss支付',
    'payment.confirm': '确认支付',
    'payment.popular': '热门',
    'payment.easyDesc': '简单快速支付',
    'payment.cardDesc': '信用卡/借记卡',
    'payment.currency': '元',
    'payment.api': 'API访问',
    'payment.feat.5holograms': '5个全息图',
    'payment.feat.50holograms': '50个全息图',
    'payment.feat.unlimitedHolograms': '无限全息图',
    'payment.feat.1gb': '1GB存储空间',
    'payment.feat.10gb': '10GB存储空间',
    'payment.feat.100gb': '100GB存储空间',
    'payment.feat.basicTheme': '基本主题',
    'payment.feat.premiumTheme': '高级主题',
    'payment.feat.allThemes': '所有主题',
    'payment.feat.prioritySupport': '优先支持',
    'payment.feat.vipSupport': 'VIP支持',
    'settings.title': '设置',
    'settings.account': '账户',
    'settings.profile': '编辑资料',
    'settings.language': '语言',
    'settings.notifications': '通知',
    'settings.push': '推送通知',
    'settings.email': '电子邮件通知',
    'settings.privacy': '隐私',
    'settings.terms': '服务条款',
    'settings.policy': '隐私政策',
    'settings.version': '版本',
    'settings.logout': '登出',
    'settings.delete': '删除账户',
    'settings.support': '支持',
    'settings.faq': '常见问题',
    'settings.contact': '联系我们',
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('ko')

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)['ko']] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}
